### ISSUE TITLE
Allow for remote Dispersion Coefficient Control

### ISSUE THREAD

**Issue by fonarevvichka** [spectralcode/octproz-socket-stream-extension#1]
I want to implement the functionality made available by the
```
void setDispCompCoeffsRequest(double* d0, double* d1, double* d2, double* d3); ///< This signal can be used to change the coeffs for numerical dispersion compensation. If parameter value is "nullptr" the respective coefficient will not be changed.
```
in the socket stream extension.

I implement a simple version on my local system with the command structured as follows:
`set_disp_coeff:<d0>:<d1>:<d2>:<d3>`

Here is the code snippet to implement that:
```
...
else if (command.startsWith("set_disp_coeff")) {
        QStringList parts = command.split(":", QString::SkipEmptyParts);
        if (parts.size() == 5) {
            bool ok1, ok2, ok3, ok4;
            double coeff1 = parts[1].toDouble(&ok1);
            double coeff2 = parts[2].toDouble(&ok2);
            double coeff3 = parts[3].toDouble(&ok3);
            double coeff4 = parts[4].toDouble(&ok4);

            if (ok1 && ok2 && ok3 && ok4) {
                emit setDispCompCoeffsRequest(&coeff1, &coeff2, &coeff3, &coeff4);
            } else {
                emit error("One or more coefficients could not be converted to a double.");
            }
        } else {
            emit error("Invalid dispersion coefficients command");
        }
...
  ```

**Comment by spectralcode** [comment]
Hi, thanks for the suggestion!
I ended up implmenting this a little bit different because 
```
void setDispCompCoeffsRequest(double* d0, double* d1, double* d2, double* d3); ///< This signal can be used to change the coeffs for numerical dispersion compensation. If parameter value is "nullptr" the respective coefficient will not be changed.
```
can also accept `nullptr` as input. In your suggested snipped however `toDouble` would return false if the input string is "nullptr".
You can have a look at the current implementaion [here](https://github.com/spectralcode/SocketStreamExtension/commit/fb7c30973a7ea1ad594f57cf7e41d818ce832058).

Let me know if you have any further suggestions or feedback!
Feel free to directly submit a pull request for any small code changes like this.

**Comment by fonarevvichka** [comment]
Sounds good, thanks for cleaning it up!
